name: Publish Template to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  synth-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
          cache: python

      - name: Setup Node 
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          architecture: "x64"
          cache: npm
                    
      - name: Install Requirements
        run: npm install -g aws-cdk # Install cdk
        run: pip install --requirement requirements.txt

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200

      - name: Synth Template
        id: data_prep
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          BUCKET_PREFIX: ${{ secrets.BUCKET_PREFIX }}
        run: rm -Rf cdk.out/ 
        run: cdk synth drift-service-catalog --path-metadata false -c drift:ArtifactBucket=$BUCKET_NAME -c drift:ArtifactBucketPrefix=$BUCKET_PREFIX > drift-service-catalog.yml

      - name: Publish Assets
        run: # cd cdk.out; for d in asset.*/ ; do base=$(basename "$d") ; cd $base ; zip -r $base.zip * ; mv "${base}.zip" .. ; cd .. ; done; cd ..
        run: # aws s3 sync cdk.out/*.zip s3://amazon-sagemaker-safe-deployment-pipeline/drift/ --acl public-read

      - name: Print Template
        run: cat drift-service-catalog.yml

      - name: Upload Template
        uses: actions/upload-artifact@v2
        with:
          name: drift-service-catalog
          path: drift-service-catalog.yml
